### ISSUE TITLE
provide a CRAN build badge

### ISSUE THREAD

**Issue by petermeissner** [metacran/metacran#50]
Github is widely used for package developement. In addition a lot of packages use TravisCI and Metacran download badges on the README cover page of their packages. 

The problem now is that the badge from Travis usually refers to the current developement version and not to the current stable version on CRAN. Wouldn't it be nice to have a badge for a packages build/check state on CRAN? 

Something structured like this? 

```
Linux            | Mac | Windows
----------------------------------------------
| ok | ok | ok | n | n | w | w | w | e | e |
----------------------------------------------
```

... or like this ... 

```
-------------------
|CRAN-Win |w|w|e|e|
-------------------

-----------------------
|CRAN-Linux |ok|ok|n|n|
-----------------------

--------------
|CRAN-OS |n|n|
--------------
```

... where ... 
- ok is for ok / color: green
- n is for note / color: light green
- w is for warning / color: yellow
- e is for error / color: red

**Comment by gaborcsardi** [comment]
Yes, I was thinking about this, too. I would need to create a DB or at least a cache that contains the state of the CRAN packages. Querying it on the fly is not really a good option.

Personally I would prefer a single badge for the whole thing, but once I have the DB, I can make this flexible. I would need a day to do this, which I don't have right now, unfortunately. Hopefully in February.

**Comment by petermeissner** [comment]
Great!

I am out of free days myself and I do not know your workflow / how you think this should be integrated into Metacran ... but if you need some small tasks accomplished / feedback / ... Give a call / mail / message and I see how I can help.

**Comment by maelle** [comment]
:wave: @petermeissner have you seen @sckott's https://github.com/ropensci/cchecksapi ? I think it does what you wished for.

**Comment by petermeissner** [comment]
@maelle your reeeally are determined on helping people - :-) - thanks, that is perfect!

@gaborcsardi Since we have a working solution for this problem now I close the issue.

**Comment by maelle** [comment]
> @maelle your reeeally are determined on helping people - :-) - thanks, that is perfect!

That's a nice way to call "reading old issue threads" 😉 Glad it helped!
