### ISSUE TITLE
Package DoE.MIParray out of sync

### ISSUE THREAD

**Issue by ugroempi** [metacran/metacran#55]
https://www.r-pkg.org/pkg/DoE.MIParray
correctly refers to the current version 0.12 of package DoE.MIParray. 
However, the linked github repository (https://github.com/cran/DoE.MIParray) is stuck at version 0.11; and - possibly as a consequence of that - the linked NEWS file on www.r-pkg.org is also outdated.

**Comment by gaborcsardi** [comment]
Thanks, updated. Some packages are out of date because of update errors. We'll have script that checks them regularly, soon.

**Comment by ugroempi** [comment]
Thanks, Gabor! https://www.r-pkg.org/pkg/DoE.MIParray#NEWS is still wrong, though.

**Comment by gaborcsardi** [comment]
It is cached, you need to wait a bit.
