### ISSUE TITLE
metacran not updating

### ISSUE THREAD

**Issue by ijlyttle** [metacran/metacran#56]
Hi,

Apologies in advance if the right answer is "just be patient". 

The [vegawidget](https://cran.r-project.org/web/packages/vegawidget/index.html) package was updated to 0.2.1 on 2019-06-24, but its [metacran entry](https://www.r-pkg.org/search.html?q=vegawidget) is still at 0.1.0.

I picked out a package, [dialrjars](https://cran.r-project.org/web/packages/dialrjars/index.html), updated on 2019-06-26; its [metacran entry](https://www.r-pkg.org/search.html?q=dialrjars) **is** updated.

Thanks,

Ian

**Comment by pbreheny** [comment]
I am also experiencing this issue, with the package [visreg](https://cran.r-project.org/web/packages/visreg/index.html).  It was updated on CRAN to 2.5-1 on 2019-06-27, but somehow, this never triggered an update to the [metacran entry](https://www.r-pkg.org/pkg/visreg).  This was a few weeks ago, so I am starting to think that the update is never going to trigger.

**Comment by gaborcsardi** [comment]
Thanks for the patience, this is now fixed. Some of the badges and other pages are cache for a short period of time, they'll also update soon.

**Comment by ijlyttle** [comment]
Looking good now, thanks @gaborcsardi!
